//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Security.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationModules = new HashSet<ApplicationModule>();
        }
    
        public string ApplicationName { get; set; }
        public string ApplicationCode { get; set; }
        public int ApplicationId { get; set; }
    
        public virtual ICollection<ApplicationModule> ApplicationModules { get; set; }
    }
}
