//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Security.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationModule
    {
        public ApplicationModule()
        {
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int ApplicationModuleId { get; set; }
        public string Name { get; set; }
        public int ApplicationId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
