//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Security.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionLevel
    {
        public PermissionLevel()
        {
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int PermissionLevelId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
