//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Security.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RoleId { get; set; }
        public int ApplicationModuleId { get; set; }
        public int PermissionLevelId { get; set; }
    
        public virtual ApplicationModule ApplicationModule { get; set; }
        public virtual PermissionLevel PermissionLevel { get; set; }
        public virtual Role Role { get; set; }
    }
}
